
POST http://localhost:8080/links HTTP/1.1
content-type: application/json

{
    "link":"https://github.com/dylang/node-rss/blob/master/lib/index.js",
    "published": false
}

###
POST http://localhost:8080/link/published HTTP/1.1
content-type: application/json

{
    "_id":"6109e08e9c47d4feabef7583",
    "published": true
}

###
GET http://localhost:8080/links HTTP/1.1

###
GET http://localhost:8080/links/popular HTTP/1.1

###
GET http://localhost:8080/links/pending HTTP/1.1

###
GET http://localhost:8080/link/2021-08-02-UITS-IT-02 HTTP/1.1
